services:
  ocean-api:
    container_name: ocean-api
    image: krre/ocean-api:1.0
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - RUST_LOG=info
    networks:
      - pg_network
      - ocean_network
    volumes:
      - ./config:/etc/ocean

  ocean-web:
    container_name: ocean-web
    image: krre/ocean-web:1.0
    restart: always
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - ADDRESS_HEADER=x-forwarded-for
      - NODE_ENV=production
    networks:
      - ocean_network
      - caddy_network
    volumes:
      - sessions:/app/.sessions

networks:
  pg_network:
    external: true
  caddy_network:
    external: true
  ocean_network:
    name: ocean_network

volumes:
  sessions:
