services:
  ocean-api:
    container_name: ocean-api
    image: krre/ocean-api:1.0
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - RUST_LOG=info
    networks:
      - postgres
      - ocean
    volumes:
      - ./config:/etc/ocean

  ocean-web:
    container_name: ocean-web
    image: krre/ocean-web:1.0
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ADDRESS_HEADER=x-forwarded-for
      - NODE_ENV=production
    networks:
      - ocean
      - caddy
    volumes:
      - sessions:/app/.sessions

networks:
  postgres:
    external: true
  caddy:
    external: true
  ocean:
    name: ocean

volumes:
  sessions:
