services:
  ocean-api:
    container_name: ocean-api
    image: krre/ocean-api:latest
    restart: always
    environment:
      - SERVER_ADDR=0.0.0.0:3000
      - POSTGRES_URL

      - ANONYM_ALLOWED
      - FRONTEND_DOMEN

      - TELEGRAM_BOT_URL
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_BOT_CHANNEL
      - TELEGRAM_BOT_ADMIN_CHAT_ID
      - TELEGRAM_BOT_ENABLED

      - WATCHDOG_ANONYM_TOKEN
      - WATCHDOG_ENABLED

      - RUST_LOG=info
    networks:
      - postgres
      - ocean

  ocean-web:
    container_name: ocean-web
    image: krre/ocean-web:latest
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ADDRESS_HEADER=x-forwarded-for
      - NODE_ENV=production
    networks:
      - ocean
      - caddy
    volumes:
      - sessions:/app/.sessions

networks:
  postgres:
    external: true
  caddy:
    external: true
  ocean:
    name: ocean

volumes:
  sessions:
