services:
  blog-api:
    container_name: blog-api
    image: krre/blog-api:1.0
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - RUST_LOG=info
    networks:
      - pg_network
      - blog_network

  blog-web:
    container_name: blog-web
    image: krre/blog-web:1.0
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production

networks:
  pg_network:
    external: true
  caddy_network:
    external: true
  blog_network:
    name: blog_network
