services:
  blog-api:
    container_name: blog-api
    image: krre/blog-api:latest
    restart: always
    environment:
      - SERVER_ADDR=0.0.0.0:3000
      - RUST_LOG=info
    networks:
      - postgres
      - blog

  blog-web:
    container_name: blog-web
    image: krre/blog-web:latest
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    networks:
    - blog
    - caddy

networks:
  postgres:
    external: true
  caddy:
    external: true
  blog:
    name: blog
