services:
  caddy:
    container_name: caddy
    image: caddy:2.11.2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - caddy_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

networks:
  caddy_network:
    name: caddy_network
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
