set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L
set langmenu=en_US.UTF-8

if has("gui_running")
    if has("gui_gtk2")
        set guifont=Inconsolata\ 12
    elseif has("gui_macvim")
        set guifont=Menlo\ Regular:h14
    elseif has("gui_win32")
        set guifont=Consolas:h11:cRUSSIAN
    else
        set guifont=Monospace
    endif
endif

