set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L
set langmenu=en_US.UTF-8
winsize 180 44
winpos 100 100

if has("gui_running")
    if has("gui_win32")
        set guifont=Courier_New:h10:cRUSSIAN
    else
        set guifont=Monospace
    endif
endif

