if has('win32')
    language English_United States
endif

colorscheme molokai
set cursorline
set number
set nocompatible

execute pathogen#infect()
syntax on
filetype plugin indent on

set tabstop=4
set shiftwidth=4
set expandtab
set showcmd "show pressed keys in normal mode
set backspace=indent,eol,start
set foldmethod=syntax
set foldlevelstart=20
set sessionoptions+=resize,winpos
set cindent

let g:session_autoload = 'yes'
let g:session_autosave = 'yes'
let g:C_UseTool_cmake = 'yes'
let NERDTreeShowBookmarks=1

nmap <C-F12> :e $MYVIMRC<cr>
nmap <C-F11> :e $MYGVIMRC<cr>
nmap <F10> :NERDTreeToggle<cr>
imap <c-q> <esc>:qa!<cr>
nmap <c-q> :qa!<cr>
nmap <c-s> :w<cr>
imap <c-s> <esc>:w<cr>a
map <F9> :CMake -j install<cr>
"swith cpp header/source
map <F4> :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>

nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

set noerrorbells visualbell t_vb=
if has ('autocmd')
    autocmd GUIEnter * set visualbell t_vb=
endif

if has('win32')
    set makeprg=mingw32-make
    let g:CMake_Executable = 'cmake.exe'
    let g:CMake_MakeTool = 'mingw32-make.exe'
endif

" remove tailing space on save any file
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

