colorscheme molokai
set cursorline
set number
set nocompatible

execute pathogen#infect()
syntax on
filetype plugin indent on

let g:session_autoload = 'yes'
let g:session_autosave = 'yes'


nmap <C-F12> :e $MYVIMRC<cr>
nmap <F12> :qa!<cr>
nmap <F2> :w<cr>

