if has('win32')
    language English_United States
endif

colorscheme molokai
set cursorline
set number
set nocompatible

execute pathogen#infect()
syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set showcmd "show pressed keys in normal mode
set sessionoptions+=resize,winpos

let g:session_autoload = 'yes'
let g:session_autosave = 'yes'

let NERDTreeShowBookmarks=1
let g:C_UseTool_cmake = 'yes'

nmap <C-F12> :e $MYVIMRC<cr>
nmap <C-F11> :e $MYGVIMRC<cr>
nmap <F10> :NERDTreeToggle<cr>
nmap <c-q> :qa!<cr>
nmap <c-s> :w<cr>
imap <c-s> <esc>:w<cr>a
inoremap jj <esc>
map <F9> :make<cr>

set noerrorbells visualbell t_vb=
if has ('autocmd')
    autocmd GUIEnter * set visualbell t_vb=
endif

if has('win32')
    set makeprg=mingw32-make
endif

" remove tailing space on save any file
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

